package org.freeciv.test;

import org.freeciv.Connect;
import org.freeciv.packet.CONN_PONG;
import org.freeciv.packet.SERVER_JOIN_REQ;

import java.io.IOException;

// Needs classes generated by GenerateTest
public class SignInAndWait {
    public static void main(String[] cmd) {
        try {
            Connect con = new Connect("127.0.0.1", 5556);

            con.toSend(new SERVER_JOIN_REQ("FreecivJava", "+Freeciv.Devel-2.4-2011.Aug.02 ", "-dev", 2L, 3L, 99L));

            System.out.println(con.getPacket());

            con.toSend(new CONN_PONG());

            System.out.println(con.getPacket());

            Thread.sleep(10000L);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
