JAVA ?= java
JAVAC ?= javac
JAR ?= jar
SCALA ?= scala
SCALAC ?= scalac
SCALALIB ?= /usr/share/java/scala-library.jar
JUNIT ?= /usr/share/java/junit4.jar:/usr/share/java/hamcrest-core.jar

GENERATEDOUT ?= autogenerated
GENERATORDEFAULTS ?= GeneratePackets/org/freeciv/packetgen/GeneratorDefaults.java
PROTOOUT ?= out/Protocol
PACKETGENOUT ?= out/GeneratePackages
TESTOUT ?= out/Tests

# take instructions from trunk.xml
VERSIONCONFIGURATION ?= trunk.xml
# assume to be placed in the top level directory of Freeciv's source code unless told otherwise
INPUTPATHPREFIX ?= ..
DEVMODE ?= true

PROTOJAR = FreecivProto.jar

all: protojar
	touch all

tests: runTests
	touch tests

compileBasicProtocol:
	mkdir -p ${PROTOOUT}
	${JAVAC} -d ${PROTOOUT} Protocol/org/freeciv/*.java Protocol/org/freeciv/packet/*.java \
	                        Protocol/org/freeciv/types/*.java Protocol/org/freeciv/packet/*/*.java
	touch compileBasicProtocol

sourceDefaultsForGenerator:
	echo "package org.freeciv.packetgen;" >> ${GENERATORDEFAULTS}
	echo "public class GeneratorDefaults {" >> ${GENERATORDEFAULTS}
	echo "  public static final String GENERATEDOUT = \"${GENERATEDOUT}\";" >> ${GENERATORDEFAULTS}
	echo "  public static final String INPUTPATHPREFIX = \"${INPUTPATHPREFIX}\";" >> ${GENERATORDEFAULTS}
	echo "  public static final String VERSIONCONFIGURATION = \"${VERSIONCONFIGURATION}\";" >> ${GENERATORDEFAULTS}
	echo "  public static final boolean DEVMODE = ${DEVMODE};" >> ${GENERATORDEFAULTS}
	echo "}" >>${GENERATORDEFAULTS}
	touch sourceDefaultsForGenerator

compileCodeGenerator: sourceDefaultsForGenerator compileBasicProtocol
	mkdir -p ${PACKETGENOUT}
	${JAVAC} -cp ${PROTOOUT}:${SCALALIB} -d ${PACKETGENOUT} GeneratePackets/org/freeciv/packetgen/*.java
	${SCALAC} -classpath ${PACKETGENOUT}:${PROTOOUT} -d ${PACKETGENOUT} GeneratePackets/org/freeciv/packetgen/*.scala
	touch compileCodeGenerator

sourceFromFreeciv: compileCodeGenerator
	${SCALA} -classpath ${PACKETGENOUT}:${PROTOOUT} org.freeciv.packetgen.GeneratePackets ${INPUTPATHPREFIX}
	touch sourceFromFreeciv

compileFromFreeciv: sourceFromFreeciv
	${JAVAC} -d ${PROTOOUT} -cp ${PROTOOUT} ${GENERATEDOUT}/org/freeciv/*/*.java ${GENERATEDOUT}/org/freeciv/*/*/*.java
	cp ${GENERATEDOUT}/org/freeciv/packet/packets.txt ${PROTOOUT}/org/freeciv/packet/
	touch compileFromFreeciv

sourceTestPeers: compileBasicProtocol compileCodeGenerator
	mkdir -p ${TESTOUT}
	${JAVAC} -d ${TESTOUT} -cp ${PACKETGENOUT}:${PROTOOUT} Tests/org/freeciv/packetgen/GenerateTest.java
	${JAVA} -cp ${TESTOUT}:${PACKETGENOUT}:${PROTOOUT} org.freeciv.packetgen.GenerateTest
	touch sourceTestPeers

# since the parser isn't finished use GenerateTest as generator
compileTestPeers: compileCodeGenerator compileBasicProtocol sourceTestPeers
	${JAVAC} -d ${PROTOOUT} -cp ${PROTOOUT} ${GENERATEDOUT}/org/freeciv/*/*.java \
	                                        ${GENERATEDOUT}/org/freeciv/*/*/*.java
	cp ${GENERATEDOUT}/org/freeciv/packet/packets.txt ${PROTOOUT}/org/freeciv/packet/
	touch compileTestPeers

protojar: compileTestPeers
	${JAR} cf ${PROTOJAR} ${PACKETGENOUT}
	touch protojar

folderTestOut:
	mkdir -p ${TESTOUT}
	touch folderTestOut

compileTestsOfGenerator: folderTestOut compileCodeGenerator
	${JAVAC} -d ${TESTOUT} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT} Tests/org/freeciv/packetgen/*.java
	${SCALAC} -d ${TESTOUT} -classpath ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} Tests/org/freeciv/packetgen/*.scala
	touch compileTestsOfGenerator

runTestsOfGenerator: compileTestsOfGenerator
	${JAVA} -ea -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.PacketsStoreTest
	${JAVA} -ea -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.CodeGenTest
	${JAVA} -ea -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.EnumTest
	${JAVA} -ea -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.DependencyStoreTest
	${SCALA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.ParseSharedTest
	${SCALA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.PacketsDefParseTest
	${SCALA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.CParserSyntaxTest
	${SCALA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.CParserSemanticTest
	${SCALA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packetgen.FromCExtractorTest
	touch runTestsOfGenerator

compileTestGeneratedCode: compileTestPeers folderTestOut
	${JAVAC} -d ${TESTOUT} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT} Tests/org/freeciv/test/*.java
	touch compileTestGeneratedCode

# not included in tests since it needs a running Freeciv server
runtestsignintoserver: compileTestGeneratedCode
	${JAVA} -cp ${PROTOOUT}:${TESTOUT} org.freeciv.test.SignInAndWait
	touch runtestsignintoserver

compilePacketTest: folderTestOut compileBasicProtocol
	${JAVAC} -d ${TESTOUT} -cp ${PROTOOUT}:${JUNIT} Tests/org/freeciv/packet/*.java
	touch compilePacketTest

runPacketTest: compilePacketTest
	${JAVA} -cp ${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.packet.PacketTest
	touch runPacketTest

runTests: compileTestGeneratedCode runTestsOfGenerator runPacketTest
	${JAVA} -cp ${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.test.GeneratedPacketTest
	${JAVA} -cp ${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.test.GeneratedEnumTest
	touch runTests

clean:
	rm -rf ${PROTOOUT} compileBasicProtocol
	rm -rf runPacketTest compilePacketTest
	rm -rf ${PACKETGENOUT} compileCodeGenerator
	rm -rf compileTestPeers
	rm -rf compileTestGeneratedCode
	rm -rf compileTestsOfGenerator
	rm -rf runTestsOfGenerator
	rm -rf runTests tests
	rm -rf folderTestOut ${TESTOUT}
	rm -rf ${GENERATEDOUT}/* sourceTestPeers
	rm -f ${PROTOJAR} protojar
	rm -f all
	rm -rf runtestsignintoserver
	rm -rf ${PROTOJAR}
	rm -rf sourceFromFreeciv
	rm -rf compiledFromFreeciv

distclean: clean
	rm -rf out ${GENERATEDOUT}
	rm -rf ${GENERATORDEFAULTS} sourceDefaultsForGenerator
