JAVA ?= java
JAVAC ?= javac
JAR ?= jar
JUNIT ?= /usr/share/java/junit4.jar

PROTOOUT ?= out/Protocol
PACKETGENOUT ?= out/GeneratePackages
TESTOUT ?= out/test

PROTOJAR = FreecivProto.jar

all: protojar

protocol:
	mkdir -p ${PROTOOUT}
	${JAVAC} -d ${PROTOOUT} Protocol/org/freeciv/*.java Protocol/org/freeciv/packet/*.java
	touch protocol

generator:
	mkdir -p ${PACKETGENOUT}
	${JAVAC} -d ${PACKETGENOUT} GeneratePackets/org/freeciv/packetgen/*.java
	touch generator

generated: generator protocol
	# since the parser isn't finished use GenerateTest as generator
	mkdir -p ${TESTOUT}
	${JAVAC} -d ${TESTOUT} -cp ${PACKETGENOUT} test/org/freeciv/test/GenerateTest.java
	${JAVA} -cp ${TESTOUT}:${PACKETGENOUT} org.freeciv.test.GenerateTest
	${JAVAC} -d ${PROTOOUT} -cp ${PROTOOUT} autogenerated/org/freeciv/packet/*.java
	touch generated

protojar: generated
	${JAR} cf ${PROTOJAR} ${PACKETGENOUT}
	touch protojar

tests: generated
	mkdir -p ${TESTOUT}
	${JAVAC} -d ${TESTOUT} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT} test/org/freeciv/test/*.java
	${JAVA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.test.PacketTest
	${JAVA} -cp ${PACKETGENOUT}:${PROTOOUT}:${JUNIT}:${TESTOUT} org.junit.runner.JUnitCore org.freeciv.test.PacketsStoreTest
	touch tests

clean:
	rm -rf ${PROTOOUT} protocol
	rm -rf ${PACKETGENOUT} generator
	rm -rf generated
	rm -rf tests ${TESTOUT}
	rm -rf autogenerated/*
	rm -f ${PROTOJAR} protojar

distclean: clean
	rm -rf out autogenerated
